services:
  nginx:
    container_name: cause-a-bracket-nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - ws
    restart: unless-stopped
  valkey:
    container_name: cause-a-bracket-valkey
    image: valkey/valkey:8.1
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
  web:
    container_name: cause-a-bracket-web
    build:
      context: .
      dockerfile: ./web/Dockerfile
    depends_on:
      - valkey
  ws:
    container_name: cause-a-bracket-ws
    build:
      context: .
      dockerfile: ./server/Dockerfile
