services:
  nginx:
    container_name: cause-a-bracket-nginx
    image: nginx:latest
    depends_on:
      - web
      - ws
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  valkey:
    container_name: cause-a-bracket-valkey
    image: valkey/valkey:8.1
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    volumes:
      - valkey_data:/data
  db:
    container_name: cause-a-bracket-db
    image: postgres:latest
    env_file:
      - ./db.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
  web:
    container_name: cause-a-bracket-web
    build:
      context: .
      dockerfile: ./web/Dockerfile
    depends_on:
      - db
      - valkey
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
  ws:
    container_name: cause-a-bracket-ws
    build:
      context: .
      dockerfile: ./server/Dockerfile
    depends_on:
      - db
      - valkey
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  db_data:
    driver: local
  valkey_data:
    driver: local
