services:
  valkey:
    container_name: cause-a-bracket-valkey
    image: valkey/valkey:8.1
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    volumes:
      - valkey_data:/data
  auth-db:
    container_name: cause-a-bracket-auth-db
    image: postgres:latest
    env_file:
      - ./auth-db.env
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    restart: unless-stopped
  app:
    container_name: cause-a-bracket-app
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - auth-db
      - valkey
volumes:
  auth_db_data:
    driver: local
  valkey_data:
    driver: local
