packages:
  - .

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild

packageExtensions:
  drizzle-kit:
    dependencies:
      drizzle-orm: "*"
