/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DescriptorsIndexRouteImport } from './routes/descriptors/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as DescriptorsIdRouteImport } from './routes/descriptors/$id'
import { Route as CategoriesIdRouteImport } from './routes/categories/$id'
import { Route as BracketsIdRouteImport } from './routes/brackets/$id'
import { ServerRoute as ApiStatusServerRouteImport } from './routes/api/status'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DescriptorsIndexRoute = DescriptorsIndexRouteImport.update({
  id: '/descriptors/',
  path: '/descriptors/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const DescriptorsIdRoute = DescriptorsIdRouteImport.update({
  id: '/descriptors/$id',
  path: '/descriptors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIdRoute = CategoriesIdRouteImport.update({
  id: '/categories/$id',
  path: '/categories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BracketsIdRoute = BracketsIdRouteImport.update({
  id: '/brackets/$id',
  path: '/brackets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusServerRoute = ApiStatusServerRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brackets/$id': typeof BracketsIdRoute
  '/categories/$id': typeof CategoriesIdRoute
  '/descriptors/$id': typeof DescriptorsIdRoute
  '/categories': typeof CategoriesIndexRoute
  '/descriptors': typeof DescriptorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brackets/$id': typeof BracketsIdRoute
  '/categories/$id': typeof CategoriesIdRoute
  '/descriptors/$id': typeof DescriptorsIdRoute
  '/categories': typeof CategoriesIndexRoute
  '/descriptors': typeof DescriptorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brackets/$id': typeof BracketsIdRoute
  '/categories/$id': typeof CategoriesIdRoute
  '/descriptors/$id': typeof DescriptorsIdRoute
  '/categories/': typeof CategoriesIndexRoute
  '/descriptors/': typeof DescriptorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brackets/$id'
    | '/categories/$id'
    | '/descriptors/$id'
    | '/categories'
    | '/descriptors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brackets/$id'
    | '/categories/$id'
    | '/descriptors/$id'
    | '/categories'
    | '/descriptors'
  id:
    | '__root__'
    | '/'
    | '/brackets/$id'
    | '/categories/$id'
    | '/descriptors/$id'
    | '/categories/'
    | '/descriptors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BracketsIdRoute: typeof BracketsIdRoute
  CategoriesIdRoute: typeof CategoriesIdRoute
  DescriptorsIdRoute: typeof DescriptorsIdRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  DescriptorsIndexRoute: typeof DescriptorsIndexRoute
}
export interface FileServerRoutesByFullPath {
  '/api/status': typeof ApiStatusServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/status': typeof ApiStatusServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/status': typeof ApiStatusServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/status' | '/api/auth/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/status' | '/api/auth/$'
  id: '__root__' | '/api/status' | '/api/auth/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiStatusServerRoute: typeof ApiStatusServerRoute
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/descriptors/': {
      id: '/descriptors/'
      path: '/descriptors'
      fullPath: '/descriptors'
      preLoaderRoute: typeof DescriptorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/descriptors/$id': {
      id: '/descriptors/$id'
      path: '/descriptors/$id'
      fullPath: '/descriptors/$id'
      preLoaderRoute: typeof DescriptorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$id': {
      id: '/categories/$id'
      path: '/categories/$id'
      fullPath: '/categories/$id'
      preLoaderRoute: typeof CategoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brackets/$id': {
      id: '/brackets/$id'
      path: '/brackets/$id'
      fullPath: '/brackets/$id'
      preLoaderRoute: typeof BracketsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BracketsIdRoute: BracketsIdRoute,
  CategoriesIdRoute: CategoriesIdRoute,
  DescriptorsIdRoute: DescriptorsIdRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  DescriptorsIndexRoute: DescriptorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiStatusServerRoute: ApiStatusServerRoute,
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
